INSERT INTO countries ("name", code)
VALUES
  ('Andorra', 'AD'),
  ('Emirados Árabes Unidos', 'AE'),
  ('Afeganistão', 'AF'),
  ('Antígua e Barbuda', 'AG'),
  ('Anguila', 'AI'),
  ('Albânia', 'AL'),
  ('Armênia', 'AM'),
  ('Angola', 'AO'),
  ('Antártida', 'AQ'),
  ('Argentina', 'AR'),
  ('Samoa Americana', 'AS'),
  ('Áustria', 'AT'),
  ('Austrália', 'AU'),
  ('Aruba', 'AW'),
  ('Ilhas Aland', 'AX'),
  ('Azerbaijão', 'AZ'),
  ('Bósnia e Herzegovina', 'BA'),
  ('Barbados', 'BB'),
  ('Bangladesh', 'BD'),
  ('Bélgica', 'BE'),
  ('Burquina Faso', 'BF'),
  ('Bulgária', 'BG'),
  ('Barein', 'BH'),
  ('Burundi', 'BI'),
  ('Benin', 'BJ'),
  ('São Bartolomeu', 'BL'),
  ('Bermudas', 'BM'),
  ('Brunei', 'BN'),
  ('Bolívia', 'BO'),
  ('Países Baixos Caribenhos', 'BQ'),
  ('Brasil', 'BR'),
  ('Bahamas', 'BS'),
  ('Butão', 'BT'),
  ('Ilha Bouvet', 'BV'),
  ('Botsuana', 'BW'),
  ('Bielorrússia', 'BY'),
  ('Belize', 'BZ'),
  ('Canadá', 'CA'),
  ('Ilhas Cocos (Keeling)', 'CC'),
  ('Congo - Kinshasa', 'CD'),
  ('República Centro-Africana', 'CF'),
  ('República do Congo', 'CG'),
  ('Suíça', 'CH'),
  ('Costa do Marfim', 'CI'),
  ('Ilhas Cook', 'CK'),
  ('Chile', 'CL'),
  ('Camarões', 'CM'),
  ('China', 'CN'),
  ('Colômbia', 'CO'),
  ('Costa Rica', 'CR'),
  ('Cuba', 'CU'),
  ('Cabo Verde', 'CV'),
  ('Curaçao', 'CW'),
  ('Ilha Christmas', 'CX'),
  ('Chipre', 'CY'),
  ('Tchéquia', 'CZ'),
  ('Alemanha', 'DE'),
  ('Djibuti', 'DJ'),
  ('Dinamarca', 'DK'),
  ('Dominica', 'DM'),
  ('República Dominicana', 'DO'),
  ('Argélia', 'DZ'),
  ('Equador', 'EC'),
  ('Estônia', 'EE'),
  ('Egito', 'EG'),
  ('Saara Ocidental', 'EH'),
  ('Eritreia', 'ER'),
  ('Espanha', 'ES'),
  ('Etiópia', 'ET'),
  ('Finlândia', 'FI'),
  ('Fiji', 'FJ'),
  ('Ilhas Malvinas', 'FK'),
  ('Micronésia', 'FM'),
  ('Ilhas Faroé', 'FO'),
  ('França', 'FR'),
  ('Gabão', 'GA'),
  ('Reino Unido', 'GB'),
  ('Granada', 'GD'),
  ('Geórgia', 'GE'),
  ('Guiana Francesa', 'GF'),
  ('Guernsey', 'GG'),
  ('Gana', 'GH'),
  ('Gibraltar', 'GI'),
  ('Groenlândia', 'GL'),
  ('Gâmbia', 'GM'),
  ('Guiné', 'GN'),
  ('Guadalupe', 'GP'),
  ('Guiné Equatorial', 'GQ'),
  ('Grécia', 'GR'),
  ('Ilhas Geórgia do Sul e Sandwich do Sul', 'GS'),
  ('Guatemala', 'GT'),
  ('Guam', 'GU'),
  ('Guiné-Bissau', 'GW'),
  ('Guiana', 'GY'),
  ('Hong Kong, RAE da China', 'HK'),
  ('Ilhas Heard e McDonald', 'HM'),
  ('Honduras', 'HN'),
  ('Croácia', 'HR'),
  ('Haiti', 'HT'),
  ('Hungria', 'HU'),
  ('Indonésia', 'ID'),
  ('Irlanda', 'IE'),
  ('Israel', 'IL'),
  ('Ilha de Man', 'IM'),
  ('Índia', 'IN'),
  ('Território Britânico do Oceano Índico', 'IO'),
  ('Iraque', 'IQ'),
  ('Irã', 'IR'),
  ('Islândia', 'IS'),
  ('Itália', 'IT'),
  ('Jersey', 'JE'),
  ('Jamaica', 'JM'),
  ('Jordânia', 'JO'),
  ('Japão', 'JP'),
  ('Quênia', 'KE'),
  ('Quirguistão', 'KG'),
  ('Camboja', 'KH'),
  ('Quiribati', 'KI'),
  ('Comores', 'KM'),
  ('São Cristóvão e Névis', 'KN'),
  ('Coreia do Norte', 'KP'),
  ('Coreia do Sul', 'KR'),
  ('Kuwait', 'KW'),
  ('Ilhas Cayman', 'KY'),
  ('Cazaquistão', 'KZ'),
  ('Laos', 'LA'),
  ('Líbano', 'LB'),
  ('Santa Lúcia', 'LC'),
  ('Liechtenstein', 'LI'),
  ('Sri Lanka', 'LK'),
  ('Libéria', 'LR'),
  ('Lesoto', 'LS'),
  ('Lituânia', 'LT'),
  ('Luxemburgo', 'LU'),
  ('Letônia', 'LV'),
  ('Líbia', 'LY'),
  ('Marrocos', 'MA'),
  ('Mônaco', 'MC'),
  ('Moldávia', 'MD'),
  ('Montenegro', 'ME'),
  ('São Martinho', 'MF'),
  ('Madagascar', 'MG'),
  ('Ilhas Marshall', 'MH'),
  ('Macedônia do Norte', 'MK'),
  ('Mali', 'ML'),
  ('Mianmar (Birmânia)', 'MM'),
  ('Mongólia', 'MN'),
  ('Macau, RAE da China', 'MO'),
  ('Ilhas Marianas do Norte', 'MP'),
  ('Martinica', 'MQ'),
  ('Mauritânia', 'MR'),
  ('Montserrat', 'MS'),
  ('Malta', 'MT'),
  ('Maurício', 'MU'),
  ('Maldivas', 'MV'),
  ('Malaui', 'MW'),
  ('México', 'MX'),
  ('Malásia', 'MY'),
  ('Moçambique', 'MZ'),
  ('Namíbia', 'NA'),
  ('Nova Caledônia', 'NC'),
  ('Níger', 'NE'),
  ('Ilha Norfolk', 'NF'),
  ('Nigéria', 'NG'),
  ('Nicarágua', 'NI'),
  ('Países Baixos', 'NL'),
  ('Noruega', 'NO'),
  ('Nepal', 'NP'),
  ('Nauru', 'NR'),
  ('Niue', 'NU'),
  ('Nova Zelândia', 'NZ'),
  ('Omã', 'OM'),
  ('Panamá', 'PA'),
  ('Peru', 'PE'),
  ('Polinésia Francesa', 'PF'),
  ('Papua-Nova Guiné', 'PG'),
  ('Filipinas', 'PH'),
  ('Paquistão', 'PK'),
  ('Polônia', 'PL'),
  ('São Pedro e Miquelão', 'PM'),
  ('Ilhas Pitcairn', 'PN'),
  ('Porto Rico', 'PR'),
  ('Territórios palestinos', 'PS'),
  ('Portugal', 'PT'),
  ('Palau', 'PW'),
  ('Paraguai', 'PY'),
  ('Catar', 'QA'),
  ('Reunião', 'RE'),
  ('Romênia', 'RO'),
  ('Sérvia', 'RS'),
  ('Rússia', 'RU'),
  ('Ruanda', 'RW'),
  ('Arábia Saudita', 'SA'),
  ('Ilhas Salomão', 'SB'),
  ('Seicheles', 'SC'),
  ('Sudão', 'SD'),
  ('Suécia', 'SE'),
  ('Singapura', 'SG'),
  ('Santa Helena', 'SH'),
  ('Eslovênia', 'SI'),
  ('Svalbard e Jan Mayen', 'SJ'),
  ('Eslováquia', 'SK'),
  ('Serra Leoa', 'SL'),
  ('San Marino', 'SM'),
  ('Senegal', 'SN'),
  ('Somália', 'SO'),
  ('Suriname', 'SR'),
  ('Sudão do Sul', 'SS'),
  ('São Tomé e Príncipe', 'ST'),
  ('El Salvador', 'SV'),
  ('Sint Maarten', 'SX'),
  ('Síria', 'SY'),
  ('Essuatíni', 'SZ'),
  ('Ilhas Turcas e Caicos', 'TC'),
  ('Chade', 'TD'),
  ('Territórios Franceses do Sul', 'TF'),
  ('Togo', 'TG'),
  ('Tailândia', 'TH'),
  ('Tadjiquistão', 'TJ'),
  ('Tokelau', 'TK'),
  ('Timor-Leste', 'TL'),
  ('Turcomenistão', 'TM'),
  ('Tunísia', 'TN'),
  ('Tonga', 'TO'),
  ('Turquia', 'TR'),
  ('Trinidad e Tobago', 'TT'),
  ('Tuvalu', 'TV'),
  ('Taiwan', 'TW'),
  ('Tanzânia', 'TZ'),
  ('Ucrânia', 'UA'),
  ('Uganda', 'UG'),
  ('Ilhas Menores Distantes dos EUA', 'UM'),
  ('Estados Unidos', 'US'),
  ('Uruguai', 'UY'),
  ('Uzbequistão', 'UZ'),
  ('Cidade do Vaticano', 'VA'),
  ('São Vicente e Granadinas', 'VC'),
  ('Venezuela', 'VE'),
  ('Ilhas Virgens Britânicas', 'VG'),
  ('Ilhas Virgens Americanas', 'VI'),
  ('Vietnã', 'VN'),
  ('Vanuatu', 'VU'),
  ('Wallis e Futuna', 'WF'),
  ('Samoa', 'WS'),
  ('Iêmen', 'YE'),
  ('Mayotte', 'YT'),
  ('África do Sul', 'ZA'),
  ('Zâmbia', 'ZM'),
  ('Zimbábue', 'ZW');
