-- migrate:up
CREATE TABLE languages (
  code CHAR(2) NOT NULL,
  "name" TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (code)
);

CREATE TABLE book_languages (
  book_id BIGINT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
  language_code CHAR(2) NOT NULL REFERENCES languages (code) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (book_id, language_code)
);

INSERT INTO languages ("name", code)
VALUES
  ('Afar', 'aa'),
  ('Abcázio', 'ab'),
  ('Africâner', 'af'),
  ('Akan', 'ak'),
  ('Albanês', 'sq'),
  ('Amárico', 'am'),
  ('Árabe', 'ar'),
  ('Aragonês', 'an'),
  ('Armênio', 'hy'),
  ('Assamês', 'as'),
  ('Avárico', 'av'),
  ('Avéstico', 'ae'),
  ('Aimará', 'ay'),
  ('Azerbaijano', 'az'),
  ('Bambara', 'bm'),
  ('Bashkir', 'ba'),
  ('Basco', 'eu'),
  ('Bielorrusso', 'be'),
  ('Bengali', 'bn'),
  ('Bislamá', 'bi'),
  ('Bósnio', 'bs'),
  ('Bretão', 'br'),
  ('Búlgaro', 'bg'),
  ('Birmanês', 'my'),
  ('Catalão', 'ca'),
  ('Chamorro', 'ch'),
  ('Checheno', 'ce'),
  ('Nianja', 'ny'),
  ('Chinês', 'zh'),
  ('Eslavo eclesiástico', 'cu'),
  ('Tchuvache', 'cv'),
  ('Córnico', 'kw'),
  ('Corso', 'co'),
  ('Cree', 'cr'),
  ('Croata', 'hr'),
  ('Tcheco', 'cs'),
  ('Dinamarquês', 'da'),
  ('Divehi', 'dv'),
  ('Holandês', 'nl'),
  ('Dzonga', 'dz'),
  ('Inglês', 'en'),
  ('Esperanto', 'eo'),
  ('Estoniano', 'et'),
  ('Ewe', 'ee'),
  ('Feroês', 'fo'),
  ('Fijiano', 'fj'),
  ('Finlandês', 'fi'),
  ('Francês', 'fr'),
  ('Frísio ocidental', 'fy'),
  ('Fula', 'ff'),
  ('Gaélico escocês', 'gd'),
  ('Galego', 'gl'),
  ('Luganda', 'lg'),
  ('Georgiano', 'ka'),
  ('Alemão', 'de'),
  ('Grego', 'el'),
  ('Groenlandês', 'kl'),
  ('Guarani', 'gn'),
  ('Guzerate', 'gu'),
  ('Haitiano', 'ht'),
  ('Hauçá', 'ha'),
  ('Hebraico', 'he'),
  ('Herero', 'hz'),
  ('Híndi', 'hi'),
  ('Hiri motu', 'ho'),
  ('Húngaro', 'hu'),
  ('Islandês', 'is'),
  ('Ido', 'io'),
  ('Igbo', 'ig'),
  ('Indonésio', 'id'),
  ('Interlíngua', 'ia'),
  ('Interlingue', 'ie'),
  ('Inuktitut', 'iu'),
  ('Inupiaque', 'ik'),
  ('Irlandês', 'ga'),
  ('Italiano', 'it'),
  ('Japonês', 'ja'),
  ('Javanês', 'jv'),
  ('Canarim', 'kn'),
  ('Canúri', 'kr'),
  ('Caxemira', 'ks'),
  ('Cazaque', 'kk'),
  ('Khmer', 'km'),
  ('Quicuio', 'ki'),
  ('Quiniaruanda', 'rw'),
  ('Quirguiz', 'ky'),
  ('Komi', 'kv'),
  ('Congolês', 'kg'),
  ('Coreano', 'ko'),
  ('Cuanhama', 'kj'),
  ('Curdo', 'ku'),
  ('Laosiano', 'lo'),
  ('Latim', 'la'),
  ('Letão', 'lv'),
  ('Limburguês', 'li'),
  ('Lingala', 'ln'),
  ('Lituano', 'lt'),
  ('Luba-catanga', 'lu'),
  ('Luxemburguês', 'lb'),
  ('Macedônio', 'mk'),
  ('Malgaxe', 'mg'),
  ('Malaio', 'ms'),
  ('Malaiala', 'ml'),
  ('Maltês', 'mt'),
  ('Manx', 'gv'),
  ('Maori', 'mi'),
  ('Marati', 'mr'),
  ('Marshalês', 'mh'),
  ('Mongol', 'mn'),
  ('Nauruano', 'na'),
  ('Navajo', 'nv'),
  ('Ndebele do norte', 'nd'),
  ('Ndebele do sul', 'nr'),
  ('Dongo', 'ng'),
  ('Nepalês', 'ne'),
  ('Norueguês', 'no'),
  ('Bokmål norueguês', 'nb'),
  ('Nynorsk norueguês', 'nn'),
  ('Sichuan yi', 'ii'),
  ('Occitânico', 'oc'),
  ('Ojibwa', 'oj'),
  ('Oriá', 'or'),
  ('Oromo', 'om'),
  ('Osseto', 'os'),
  ('Páli', 'pi'),
  ('Pashto', 'ps'),
  ('Persa', 'fa'),
  ('Polonês', 'pl'),
  ('Português', 'pt'),
  ('Panjabi', 'pa'),
  ('Quíchua', 'qu'),
  ('Romeno', 'ro'),
  ('Romanche', 'rm'),
  ('Rundi', 'rn'),
  ('Russo', 'ru'),
  ('Sami setentrional', 'se'),
  ('Samoano', 'sm'),
  ('Sango', 'sg'),
  ('Sânscrito', 'sa'),
  ('Sardo', 'sc'),
  ('Sérvio', 'sr'),
  ('Xona', 'sn'),
  ('Sindi', 'sd'),
  ('Cingalês', 'si'),
  ('Eslovaco', 'sk'),
  ('Esloveno', 'sl'),
  ('Somali', 'so'),
  ('Soto do sul', 'st'),
  ('Espanhol', 'es'),
  ('Sundanês', 'su'),
  ('Suaíli', 'sw'),
  ('Suázi', 'ss'),
  ('Sueco', 'sv'),
  ('Filipino', 'tl'),
  ('Taitiano', 'ty'),
  ('Tadjique', 'tg'),
  ('Tâmil', 'ta'),
  ('Tártaro', 'tt'),
  ('Télugo', 'te'),
  ('Tailandês', 'th'),
  ('Tibetano', 'bo'),
  ('Tigrínia', 'ti'),
  ('Tonganês', 'to'),
  ('Tsonga', 'ts'),
  ('Tswana', 'tn'),
  ('Turco', 'tr'),
  ('Turcomeno', 'tk'),
  ('Akan', 'tw'),
  ('Uigur', 'ug'),
  ('Ucraniano', 'uk'),
  ('Urdu', 'ur'),
  ('Uzbeque', 'uz'),
  ('Venda', 've'),
  ('Vietnamita', 'vi'),
  ('Volapuque', 'vo'),
  ('Valão', 'wa'),
  ('Galês', 'cy'),
  ('Uolofe', 'wo'),
  ('Xhosa', 'xh'),
  ('Iídiche', 'yi'),
  ('Iorubá', 'yo'),
  ('Zhuang', 'za'),
  ('Zulu', 'zu');

-- migrate:down
DROP TABLE book_languages;
DROP TABLE languages;
