name: CI

on:
  workflow_call:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: isis_test
          POSTGRES_USER: isis
          POSTGRES_PASSWORD: isis
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U isis -d isis_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      DATABASE_URL: postgres://isis:isis@localhost:5432/isis_test?sslmode=disable

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Typescript
        run: npm run tsc

      - name: Build
        run: npm run build

      - name: Migrate database
        run: npm run db:wait -w api && npm run db:up -w api

      - name: Lint
        run: npm run lint

